commands_dir: commands
show_examples_on_error: true
strict: set -eo pipefail

enable_view_markers: always
enable_env_var_names_array: never
enable_deps_array: never

usage_colors:
  caption: bold
  command: green
  arg: green
  flag: green
  environment_variable: green
